image: node:latest

before_script:
  - yarn

cache:
  paths:
    - node_modules/

stages:
  - lint
  - deploy

lint:
  stage: lint
  script:
    - yarn lint

publish:
  stage: deploy
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm version
    - yarn publish-minor
